# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# set the default branch
# default: empty, the default branch on GitHub
branch: develop

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every week"

# search for requirement files
# default: True
# allowed: True, False
search: True

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
requirements:

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs: enhancement

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
assignees:

# configure the branch prefix the bot is using
# default: pyup-
branch_prefix: pyup-

# set a global prefix for PRs
# default: empty
pr_prefix:

# allow to close stale PRs
# default: True
close_prs: True
