checks:
  python:
    code_rating: true
    # duplicate_code: true
    basic_dangerous_default_value: true
    basic_eval_used: true
    basic_lost_exception: true
    classes_bad_classmethod_argument: true
    classes_bad_mcs_classmethod_argument: true
    classes_bad_mcs_method_argument: true
    classes_bad_staticmethod_argument: true
    classes_no_self_argument: true
    classes_protected_access: true
    classes_signature_differs: true
    variables_unpacking_non_sequence: true
    variables_undefined_variable: true
    variables_redefined_builtin: true
    variables_global_at_module_level: true
    logging_not_lazy: true
    exceptions_raising_non_exception: true
    exceptions_notimplemented_raised: true
    exceptions_broad_except: true
    exceptions_bare_except: true
    basic_exec_used: true
    variables_redefined_outer_name: true
    variables_redefine_in_handler: true
    imports_import_error: true
    variables_used_before_assignment: true
    variables_undefined_loop_variable: true
    variables_undefined_all_variable: true
    variables_unbalanced_tuple_unpacking: true
    variables_no_name_in_module: true
    variables_global_variable_undefined: true
    typecheck_unexpected_keyword_arg: true
    typecheck_too_many_function_args: true
    typecheck_not_callable: true
    typecheck_no_value_for_parameter: true
    typecheck_no_member: true
    typecheck_duplicate_keyword_arg: true
    typecheck_assignment_from_no_return: true
    string_too_many_format_args: true
    string_constant_anomalous_unicode_escape_in_string: true
    open_mode_bad_open_mode: true
    logging_too_many_args: true
    imports_import_self: true
    exceptions_raising_bad_type: true
    exceptions_catching_non_exception: true
    classes_non_parent_init_called: true
    classes_non_iterator_returned: true
    classes_bad_context_manager: true
    classes_access_member_before_definition: true
    basic_return_in_init: true
    basic_not_in_loop: true
    basic_function_redefined: true
    basic_bad_reversed_sequence: true
    basic_abstract_class_instantiated: true
    string_constant_anomalous_backslash_in_string: true
    newstyle_bad_super_call: true
    imports_cyclic_import: true
    classes_super_init_not_called: true
    classes_method_hidden: true
    classes_arguments_differ: true
    basic_useless_else_on_loop: true
    basic_expression_not_assigned: true
tools:
  pylint:
    python_version: '3'
    # config_file: .pylintrc
filter:
  excluded_paths:
    - '*/plugins/*'
    - 'docs/'
    - 'tests/'
