// Autogenerated, do not edit!
/*jslint -W070: false*/
define([], function() {
  'use strict';
  return {
    Connection: {'All': 0, 'Resumable': 1, 'Secure': 2},
    DownloadState: {'Failed': 3, 'All': 0, 'Unmanaged': 4, 'Finished': 1, 'Unfinished': 2},
    DownloadStatus: {'NotPossible': 13, 'FileMismatch': 15, 'Downloading': 10, 'Missing': 14, 'NA': 0, 'Processing': 18, 'Waiting': 9, 'Decrypting': 17, 'Paused': 4, 'Failed': 7, 'Finished': 5, 'Skipped': 6, 'Unknown': 20, 'Aborted': 12, 'Online': 2, 'Starting': 8, 'TempOffline': 11, 'Offline': 1, 'Custom': 19, 'Occupied': 16, 'Queued': 3},
    FileStatus: {'Remote': 2, 'Ok': 0, 'Missing': 1},
    InputType: {'PluginList': 15, 'Multiple': 13, 'TimeSpan': 8, 'Int': 2, 'ByteSize': 9, 'Time': 7, 'List': 14, 'Textbox': 5, 'Bool': 10, 'File': 3, 'NA': 0, 'Table': 16, 'Folder': 4, 'Password': 6, 'Click': 11, 'Select': 12, 'Text': 1},
    Interaction: {'Captcha': 2, 'All': 0, 'Query': 4, 'Notification': 1},
    MediaType: {'All': 0, 'Audio': 2, 'Image': 4, 'Executable': 64, 'Other': 1, 'Video': 8, 'Document': 16, 'Archive': 32},
    PackageStatus: {'Paused': 1, 'Remote': 3, 'Folder': 2, 'Ok': 0},
    Permission: {'All': 0, 'Interaction': 32, 'Modify': 4, 'Add': 1, 'Accounts': 16, 'Plugins': 64, 'Download': 8, 'Delete': 2},
    ProgressType: {'LinkCheck': 8, 'All': 0, 'FileOperation': 32, 'Decrypting': 4, 'Other': 1, 'Download': 2, 'Addon': 16},
    Role: {'Admin': 0, 'User': 1},
  };
});
