# -*- coding: utf-8 -*-

#
# Autogenerated by Thrift Compiler (0.9.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:slots,dynamic
#

from thrift.Thrift import TException, TMessageType, TType

from pyload.remote.thriftbackend.thriftgen.pyload.ttypes import *
